'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {ArrowRight,ChevronDown,Instagram,Menu,Minus,Plus,ShoppingBag,X} from 'lucide-react';
import {logo,images,services,products,testimonials} from '@/lib/data';
import Modal from '@/components/Modal';
import Field from '@/components/Field';

const nav=[['Home','home'],['About','about'],['Services','services'],['Products','products'],['Consultation','consultation'],['Contact','contact']];
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)); const load=(k,d=null)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};

export default function Page(){
 const [menu,setMenu]=useState(false),[auth,setAuth]=useState(false),[user,setUser]=useState(null),[authMode,setAuthMode]=useState('login'),[booking,setBooking]=useState(null),[consult,setConsult]=useState(false),[product,setProduct]=useState(null),[account,setAccount]=useState(false),[newsletter,setNewsletter]=useState(false),[toast,setToast]=useState('');
 const [authForm,setAuthForm]=useState({email:'',password:''}),[bookForm,setBookForm]=useState({date:'',time:'',name:'',phone:'',note:''}),[consultForm,setConsultForm]=useState({name:'',phone:'',concern:'',date:'',time:''}),[email,setEmail]=useState('');
 useEffect(()=>{setUser(load('aureliaUser'));},[]);
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(''),3500)};
 const go=id=>{setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
 const submitNewsletter=e=>{e.preventDefault();if(!/^\S+@\S+\.\S+$/.test(email))return notify('Please enter a valid email address.');save('aureliaNewsletter',email);setEmail('');setNewsletter(true);notify('You’re on the list — welcome to AURELIA.');};
 const login=e=>{e.preventDefault();if(!authForm.email||!authForm.password)return notify('Please complete both fields.');const u={email:authForm.email};save('aureliaUser',u);setUser(u);setAuth(false);setAuthForm({email:'',password:''});notify('Welcome back. Your member benefits are now unlocked.');};
 const logout=()=>{localStorage.removeItem('aureliaUser');setUser(null);setAccount(false);notify('You have been logged out.');};
 const startBooking=s=>{if(!user){setBooking({service:s,gate:true});return;}setBookForm({date:'',time:'',name:'',phone:'',note:''});setBooking({service:s,gate:false});};
 const submitBooking=e=>{e.preventDefault();if(!bookForm.date||!bookForm.time||!bookForm.name||!bookForm.phone)return notify('Please complete the required booking fields.');const ref='AUR-'+Math.random().toString(36).slice(2,8).toUpperCase();const old=load('aureliaBookings',[]);save('aureliaBookings',[...old,{...bookForm,service:booking.service.name,ref}]);setBooking(null);notify(`Booking confirmed. Reference: ${ref}`);};
 const submitConsult=e=>{e.preventDefault();if(!consultForm.name||!consultForm.phone||!consultForm.concern||!consultForm.date||!consultForm.time)return notify('Please complete the consultation form.');save('aureliaConsultations',[...(load('aureliaConsultations',[])),consultForm]);setConsult(false);setConsultForm({name:'',phone:'',concern:'',date:'',time:''});notify('Consultation request received. We’ll take it from here.');};
 return <main>
 <header className="fixed top-0 z-50 w-full border-b border-white/15 bg-black/80 text-white backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><button onClick={()=>go('home')} className="flex items-center"><Image src={logo} alt="AURELIA logo" width={130} height={44} className="h-9 w-auto object-contain brightness-125"/></button><nav className="hidden items-center gap-7 lg:flex">{nav.map(([label,id])=><button key={id} onClick={()=>go(id)} className="text-xs uppercase tracking-[.14em] text-white/70 transition hover:text-white">{label}</button>)}</nav><div className="hidden items-center gap-3 lg:flex">{user?<button onClick={()=>setAccount(true)} className="border border-white/30 px-4 py-2 text-xs uppercase tracking-widest hover:bg-white hover:text-black">Account</button>:<button onClick={()=>setAuth(true)} className="border border-white/30 px-4 py-2 text-xs uppercase tracking-widest hover:bg-white hover:text-black">Login</button>}<button onClick={()=>go('services')} className="bg-white px-4 py-2 text-xs font-semibold uppercase tracking-widest text-black">Book</button></div><button className="lg:hidden" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="border-t border-white/10 bg-black px-5 py-5 lg:hidden">{nav.map(([label,id])=><button key={id} onClick={()=>go(id)} className="block w-full border-b border-white/10 py-4 text-left text-sm uppercase tracking-widest text-white/80">{label}</button>)}<button onClick={()=>{setMenu(false);setAuth(true)}} className="mt-5 w-full bg-white py-3 text-sm font-semibold uppercase tracking-widest text-black">{user?'Account':'Login / Account'}</button></div>}</header>
 <section id="home" className="relative min-h-[760px] overflow-hidden bg-black text-white"><Image src={images.hero} alt="Luxury spa interior" fill priority className="object-cover opacity-80"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/35 to-white/10 opacity-90"/><div className="relative mx-auto grid min-h-[760px] max-w-7xl items-end px-5 pb-16 pt-32 lg:grid-cols-2 lg:items-center lg:px-8"><div className="reveal max-w-2xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[.32em] text-white/60">Private wellness · Lagos</p><h1 className="font-[Manrope] text-5xl font-medium leading-[.95] tracking-[-.05em] sm:text-7xl lg:text-8xl">A quieter way<br/>to feel <i>well.</i></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/70 sm:text-lg">Thoughtful treatments, expert hands and an atmosphere designed to make time slow down.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>go('services')} className="group bg-white px-6 py-3.5 text-sm font-semibold text-black">Explore Services <ArrowRight className="ml-4 inline transition group-hover:translate-x-1" size={17}/></button><button onClick={()=>setConsult(true)} className="border border-white/40 px-6 py-3.5 text-sm font-medium hover:bg-white/10">Book a Consultation</button></div><form onSubmit={submitNewsletter} className="mt-12 max-w-lg"><p className="mb-3 text-xs text-white/50">Be the first to know about exclusive treatments, seasonal rituals and private offers.</p><div className="flex border-b border-white/40 py-2"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Your email address" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/45"/><button className="text-xs font-semibold uppercase tracking-widest">Get Updates</button></div></form></div></div></section>
 <section id="about" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div className="reveal"><p className="mb-5 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">The AURELIA philosophy</p><h2 className="font-[Manrope] text-4xl font-medium tracking-[-.04em] sm:text-6xl">Care that feels<br/><i>personal.</i></h2><p className="mt-7 max-w-lg text-base leading-8 text-neutral-600">We believe wellness is not a performance. It is a practice of paying attention — to your body, your skin, your breath and the small rituals that return you to yourself.</p></div><div className="grid gap-5 sm:grid-cols-[1.2fr_.8fr]"><div className="relative min-h-[440px]"><Image src={images.about} alt="Spa treatment" fill className="object-cover"/></div><div className="flex flex-col justify-between border-t border-black pt-5 sm:border-l sm:border-t-0 sm:pl-6"><div><p className="text-4xl font-medium">01</p><p className="mt-2 text-sm text-neutral-500">Personalized care</p></div><div><p className="text-4xl font-medium">02</p><p className="mt-2 text-sm text-neutral-500">Expert therapists</p></div><div><p className="text-4xl font-medium">03</p><p className="mt-2 text-sm text-neutral-500">Premium products</p></div><div><p className="text-4xl font-medium">04</p><p className="mt-2 text-sm text-neutral-500">Calm environment</p></div></div></div></div></section>
 <section id="services" className="bg-white px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">Our treatments</p><h2 className="font-[Manrope] text-4xl font-medium tracking-[-.04em] sm:text-6xl">Made for your<br/><i>next exhale.</i></h2></div><p className="max-w-sm text-sm leading-6 text-neutral-500">Choose a ritual. Stay for the feeling.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{services.map(s=><article key={s.name} className="group border border-neutral-200 bg-[#faf9f6] transition hover:-translate-y-1 hover:border-black"><div className="relative aspect-[4/5] overflow-hidden"><Image src={s.image} alt={s.name} fill className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent"/><div className="absolute bottom-0 left-0 p-5 text-white"><p className="text-[10px] uppercase tracking-[.2em] text-white/60">{s.duration}</p><h3 className="mt-1 text-xl font-medium">{s.name}</h3></div></div><div className="p-5"><p className="min-h-14 text-sm leading-6 text-neutral-600">{s.desc}</p><div className="mt-5 flex items-center justify-between border-t border-neutral-200 pt-4"><span className="font-medium">{s.price}</span><button onClick={()=>startBooking(s)} className="text-xs font-semibold uppercase tracking-widest underline underline-offset-4">Book Service</button></div></div></article>)}</div></div></section>
 <Editorial title="Massage" copy="Release tension. Restore balance. Our massage rituals are paced deliberately, with techniques selected around how your body feels today." image={images.massage} reverse={false} onClick={()=>go('services')}/>
 <Editorial title="Facial Treatments" copy="Skin is a living story. Our facial rituals combine careful touch, premium formulations and a quiet consultation before every treatment." image={images.facial} reverse onClick={()=>go('services')}/>
 <section id="products" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="flex items-end justify-between gap-6"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">At-home rituals</p><h2 className="font-[Manrope] text-4xl font-medium tracking-[-.04em] sm:text-6xl">Shop <i>wellness.</i></h2></div><button className="hidden border border-black px-5 py-3 text-xs font-semibold uppercase tracking-widest sm:block">View All Products</button></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=><article key={p.name} className="group"><button onClick={()=>setProduct(p)} className="w-full text-left"><div className="relative aspect-square overflow-hidden bg-neutral-100"><Image src={p.image} alt={p.name} fill className="object-cover transition duration-700 group-hover:scale-105"/></div><div className="flex items-start justify-between gap-4 pt-4"><div><h3 className="font-medium">{p.name}</h3><p className="mt-1 text-sm text-neutral-500">{p.desc}</p></div><span className="whitespace-nowrap text-sm">{p.price}</span></div></button></article>)}</div><button className="mt-8 w-full border border-black px-5 py-4 text-xs font-semibold uppercase tracking-widest sm:hidden">View All Products</button></section>
 <section className="bg-black px-5 py-20 text-white lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="mb-3 text-xs uppercase tracking-[.25em] text-white/45">Member benefits</p><h2 className="font-[Manrope] text-4xl font-medium tracking-[-.04em] sm:text-5xl">Make wellness a <i>ritual.</i></h2><p className="mt-4 max-w-xl text-sm leading-6 text-white/60">Members receive exclusive discounts, priority booking, special treatment offers and seasonal promotions.</p></div>{user?<div className="border border-white/20 p-6 sm:min-w-80"><p className="text-xs uppercase tracking-widest text-white/50">Member access</p><p className="mt-3 text-lg">10% off selected treatments</p><p className="mt-1 text-sm text-white/55">Priority booking · seasonal offers</p></div>:<button onClick={()=>setAuth(true)} className="border border-white/30 px-6 py-4 text-xs font-semibold uppercase tracking-widest hover:bg-white hover:text-black">Join to Unlock Benefits</button>}</div></section>
 <section id="consultation" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-10 border-y border-black py-12 lg:grid-cols-[1fr_.7fr] lg:items-center"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">Need guidance?</p><h2 className="font-[Manrope] text-4xl font-medium tracking-[-.04em] sm:text-6xl">Speak with a <i>specialist.</i></h2></div><div><p className="text-sm leading-7 text-neutral-600">Not sure what your skin or body needs? Tell us what you are experiencing and we’ll help you find the right ritual.</p><button onClick={()=>setConsult(true)} className="mt-6 bg-black px-6 py-3.5 text-sm font-semibold text-white">Book a Consultation <ArrowRight className="ml-4 inline" size={17}/></button></div></div></section>
 <section className="bg-white px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-xl"><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">Quietly recommended</p><h2 className="font-[Manrope] text-4xl font-medium tracking-[-.04em] sm:text-6xl">Words from our <i>guests.</i></h2></div><div className="mt-12 grid gap-0 md:grid-cols-2 lg:grid-cols-4">{testimonials.map(([q,n,t])=><div key={n} className="border-t border-neutral-200 p-6 first:pl-0 lg:border-l lg:border-t-0 lg:first:border-l-0"><p className="text-lg leading-8">{q}</p><div className="mt-10"><p className="text-sm font-semibold">{n}</p><p className="mt-1 text-xs uppercase tracking-widest text-neutral-500">{t}</p></div></div>)}</div></div></section>
 <FAQ/>
 <section id="contact" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-2"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">Visit AURELIA</p><h2 className="font-[Manrope] text-5xl font-medium tracking-[-.05em] sm:text-7xl">Come back<br/><i>to yourself.</i></h2></div><div className="grid gap-8 sm:grid-cols-2"><ContactItem title="Address">12 Serenity Lane<br/>Victoria Island, Lagos</ContactItem><ContactItem title="Contact">+234 800 000 0000<br/>hello@aurelia.example</ContactItem><ContactItem title="Hours">Mon–Fri · 9am–8pm<br/>Sat–Sun · 10am–7pm</ContactItem><ContactItem title="Social">Instagram<br/>TikTok<br/>Facebook</ContactItem></div></div></section>
 <footer className="bg-black px-5 py-14 text-white lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.4fr_1fr_1fr_1.2fr]"><div><Image src={logo} alt="AURELIA logo" width={130} height={44} className="h-9 w-auto object-contain brightness-150"/><p className="mt-5 max-w-sm text-sm leading-6 text-white/50">A considered space for body, skin and mind. Luxury wellness without the noise.</p></div><FooterLinks title="Explore" links={nav.slice(0,5)}/><FooterLinks title="Treatments" links={services.slice(0,5).map(s=>[s.name,'services'])}/><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/50">Stay close</p><p className="mt-4 text-sm text-white/60">Seasonal rituals, member offers and notes from the studio.</p><form onSubmit={submitNewsletter} className="mt-5 flex border-b border-white/30 py-2"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-white/40"/><button aria-label="Subscribe"><ArrowRight size={18}/></button></form></div></div><div className="mx-auto mt-12 flex max-w-7xl flex-col justify-between gap-3 border-t border-white/10 pt-6 text-[11px] uppercase tracking-widest text-white/35 sm:flex-row"><span>© 2026 AURELIA Wellness</span><span>Frontend demonstration · No real bookings are processed</span></div></footer>
 {toast&&<div className="fixed bottom-5 left-1/2 z-[120] -translate-x-1/2 bg-black px-5 py-3 text-sm text-white shadow-xl">{toast}</div>}
 <Modal open={auth} onClose={()=>setAuth(false)} title={authMode==='login'?'Welcome back':'Create your member account'}><form onSubmit={login} className="grid gap-5"><Field label="Email" type="email" value={authForm.email} onChange={e=>setAuthForm({...authForm,email:e.target.value})} placeholder="you@example.com"/><Field label="Password" type="password" value={authForm.password} onChange={e=>setAuthForm({...authForm,password:e.target.value})} placeholder="••••••••"/><button className="bg-black py-3.5 text-sm font-semibold text-white">{authMode==='login'?'Login':'Create Account'}</button><button type="button" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')} className="text-center text-sm text-neutral-500 underline underline-offset-4">{authMode==='login'?'New here? Create Account':'Already a member? Login'}</button><p className="text-center text-xs text-neutral-400">Demo only — credentials are stored locally in your browser.</p></form></Modal>
 <Modal open={booking?.gate} onClose={()=>setBooking(null)} title="Member access required"><p className="text-sm leading-7 text-neutral-600">Please log in to continue with your booking and unlock member benefits.</p><div className="mt-6 flex gap-3"><button onClick={()=>{setBooking(null);setAuth(true)}} className="flex-1 bg-black py-3 text-sm font-semibold text-white">Login</button><button onClick={()=>setBooking(null)} className="flex-1 border border-neutral-300 py-3 text-sm">Cancel</button></div></Modal>
 <Modal open={!!booking&&!booking.gate} onClose={()=>setBooking(null)} title={`Book ${booking?.service.name||''}`}><form onSubmit={submitBooking} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Preferred date" type="date" value={bookForm.date} onChange={e=>setBookForm({...bookForm,date:e.target.value})}/><Field label="Preferred time" type="time" value={bookForm.time} onChange={e=>setBookForm({...bookForm,time:e.target.value})}/></div><Field label="Name" value={bookForm.name} onChange={e=>setBookForm({...bookForm,name:e.target.value})}/><Field label="Phone number" value={bookForm.phone} onChange={e=>setBookForm({...bookForm,phone:e.target.value})}/><label className="grid gap-2 text-sm font-medium">Optional note<textarea rows="3" value={bookForm.note} onChange={e=>setBookForm({...bookForm,note:e.target.value})} className="border border-neutral-300 px-4 py-3 outline-none focus:border-black"/></label><button className="bg-black py-3.5 text-sm font-semibold text-white">Confirm Booking</button><p className="text-center text-xs text-neutral-400">Frontend demonstration. Your request is saved locally.</p></form></Modal>
 <Modal open={consult} onClose={()=>setConsult(false)} title="Book a Consultation"><form onSubmit={submitConsult} className="grid gap-4"><Field label="Full name" value={consultForm.name} onChange={e=>setConsultForm({...consultForm,name:e.target.value})}/><Field label="Phone number" value={consultForm.phone} onChange={e=>setConsultForm({...consultForm,phone:e.target.value})}/><label className="grid gap-2 text-sm font-medium">Skin concern or what you'd like help with<textarea rows="4" value={consultForm.concern} onChange={e=>setConsultForm({...consultForm,concern:e.target.value})} placeholder="Tell us briefly about your skin concern or what you'd like help with..." className="border border-neutral-300 px-4 py-3 outline-none focus:border-black"/></label><div className="grid gap-4 sm:grid-cols-2"><Field label="Preferred date" type="date" value={consultForm.date} onChange={e=>setConsultForm({...consultForm,date:e.target.value})}/><Field label="Preferred time" type="time" value={consultForm.time} onChange={e=>setConsultForm({...consultForm,time:e.target.value})}/></div><button className="bg-black py-3.5 text-sm font-semibold text-white">Request Consultation</button></form></Modal>
 <Modal open={!!product} onClose={()=>setProduct(null)} title={product?.name||''}>{product&&<><div className="relative aspect-[4/3] overflow-hidden bg-neutral-100"><Image src={product.image} alt={product.name} fill className="object-cover"/></div><div className="mt-5 flex justify-between gap-5"><p className="text-sm leading-6 text-neutral-600">{product.desc}</p><p className="font-medium">{product.price}</p></div><button onClick={()=>{setProduct(null);notify('Product added to your demo bag.')}} className="mt-6 flex w-full items-center justify-center gap-2 bg-black py-3.5 text-sm font-semibold text-white"><ShoppingBag size={17}/> Add to Bag</button></>}</Modal>
 <Modal open={account} onClose={()=>setAccount(false)} title="Your account"><div className="space-y-5"><div className="border border-neutral-200 p-5"><p className="text-xs uppercase tracking-widest text-neutral-400">Member</p><p className="mt-2 font-medium">{user?.email}</p></div><div><p className="text-xs uppercase tracking-widest text-neutral-400">Bookings</p>{load('aureliaBookings',[]).filter(b=>b).length?<div className="mt-3 space-y-2">{load('aureliaBookings',[]).map(b=><div key={b.ref} className="border border-neutral-200 p-4 text-sm"><b>{b.service}</b><br/>{b.date} · {b.time}<br/><span className="text-xs text-neutral-500">Ref: {b.ref}</span></div>)}</div>:<p className="mt-2 text-sm text-neutral-500">No bookings yet.</p>}</div><button onClick={logout} className="w-full border border-black py-3 text-sm font-semibold">Log out</button></div></Modal>
 </main>
}
function Editorial({title,copy,image,reverse,onClick}){return <section className="px-5 py-20 lg:px-8 lg:py-28"><div className={`mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2 lg:gap-20 ${reverse?'lg:[&>*:first-child]:order-2':''}`}><div className="relative aspect-[4/3] overflow-hidden"><Image src={image} alt={title} fill className="object-cover"/></div><div className="max-w-lg"><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">Featured ritual</p><h2 className="font-[Manrope] text-5xl font-medium tracking-[-.05em] sm:text-7xl">{title}</h2><p className="mt-6 text-base leading-8 text-neutral-600">{copy}</p><button onClick={onClick} className="mt-8 border-b border-black pb-2 text-sm font-semibold">Discover {title} <ArrowRight className="ml-4 inline" size={16}/></button></div></div></section>}
function FAQ(){const qs=['Do I need an appointment?','Can I book without an account?','What should I bring to my appointment?','Do you offer consultations?','What happens if I need to cancel?','How do member discounts work?'];const [open,setOpen]=useState(null);return <section className="bg-[#ebeae5] px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1fr]"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.25em] text-neutral-500">Questions, answered</p><h2 className="font-[Manrope] text-4xl font-medium tracking-[-.04em] sm:text-6xl">The details<br/>matter.</h2></div><div>{qs.map((q,i)=><div key={q} className="border-t border-black/15"><button onClick={()=>setOpen(open===i?null:i)} className="flex w-full items-center justify-between py-5 text-left text-sm font-medium">{q}{open===i?<Minus size={18}/>:<Plus size={18}/>}</button>{open===i&&<p className="pb-5 pr-10 text-sm leading-7 text-neutral-600">Yes — and we recommend reserving ahead when possible. This frontend demo does not connect to a live scheduling system; requests are saved locally in your browser.</p>}</div>)}</div></div></section>}
function ContactItem({title,children}){return <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-neutral-400">{title}</p><p className="mt-3 text-sm leading-7 text-neutral-700">{children}</p></div>}
function FooterLinks({title,links}){return <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/50">{title}</p><div className="mt-4 grid gap-3">{links.map(([label,id])=><a key={label} href={'#'+id} className="text-sm text-white/65 transition hover:text-white">{label}</a>)}</div></div>}
